<?php

namespace AppBundle\Repository;
use Symfony\Component\HttpFoundation\Request;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductsByIdArray($idArray){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('p');
        $qb->from('AppBundle:Product', 'p');
        $qb->where($qb->expr()->in('p.id', $idArray));
        return $qb->getQuery()->getResult();
    }
}